services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend-with-auth/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_started
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend-auth-code/Dockerfile
    ports:
      - "3000:3000"
    extra_hosts:
      - "localhost:host-gateway" # allows the backend to call services on the host machine using localhost (necessary for auth server discovery and for the frontend to call the backend using the EXTERNAL_URI)
    environment:
      - EXTERNAL_URI=http://localhost:3000
      - FRONTEND_URL=http://localhost:8080
      - MCP_BASE_URL=http://mcp-server:3000 # used internally to call the MCP server
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5:3b}
      - OLLAMA_BASE_URL=http://ollama:11434 # used internally to call the Ollama server
    depends_on:
      mcp-server:
        condition: service_started
      ollama:
        condition: service_healthy
  mcp-server:
    container_name: mcp-server
    build:
      context: .
      dockerfile: apps/mcp-server-with-auth/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - EXTERNAL_URI=http://localhost:3001
      - OIDC_ISSUER_URL=http://localhost:3002 # used externally (for other services to discover the auth server)
      - OIDC_JWKS_URL=http://auth-server:3000/.well-known/jwks.json # used internally (to fetch the JWKS from the auth server)
  auth-server:
    container_name: auth-server
    build:
      context: .
      dockerfile: apps/auth-server/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - EXTERNAL_URI=http://localhost:3002

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    # list models to check if the server is healthy
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./.docker-compose/ollama/data:/root/.ollama
    # ollama doesn't have a built-in way to run a model on startup,
    # so we use the entrypoint to start the server and then run the model
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama run ${OLLAMA_MODEL:-qwen2.5:3b} && wait"
